services:
  - type: web
    name: precificador-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: SECRET_KEY
        value: GxJv53xIsMwcm10F1F_PsvY9DhTCCPGRr4AornpoEWU

  - type: web
    name: precificador-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: serve -s dist
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://precificador-lika.onrender.com/api/fretes